name: "Run edge project"
on:
  workflow_dispatch:
    
jobs:
    run_edge:
        name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
              node_version: ['10', '12', '14']
              os: [ubuntu-latest, windows-latest, macOS-latest]
        env:
          EDGE_USE_CORECLR: 1

        steps:
        - uses: actions/checkout@v2
        - name: Setup Node ${{ matrix.node_version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node_version }}
        - name: Install Dependencies
          run: npm install
        - name: Build DotNet Core
          run: dotnet build src/QuickStart.sln
        - name: Run Edge
          run: npm run start:core
